
import { Component } from '@angular/core';
import { NavigationExtras, Router } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.page.html',
  styleUrls: ['./home.page.scss'],
})
export class HomePage {
  // LISTA DE ALBUMES
  albums: any [] = [
    {
      nombre: 'Wings',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$21.990',
      portada: 'assets/icon/wings.jpg',
    },
    {
      nombre: 'Layover',
      artista: 'V',
      genero: 'K-pop',
      precio: '$16.990',
      portada: 'assets/icon/layover.jpg',
    },
    {
      nombre: 'Proof',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$79.990',
      portada: 'assets/icon/proof.jpg',
    },
    {
      nombre: 'Butter',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$26.990',
      portada: 'assets/icon/butter.jpg',
    },
    {
      nombre: 'Love Yourself Her',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$23.990',
      portada: 'assets/icon/love_your_her.jpg',
    },
    {
      nombre: 'Love Yourself Tear',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$23.990',
      portada: 'assets/icon/love_your_tear.jpg',
    },
    {
      nombre: 'Love Yourself Answer',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$24.990',
      portada: 'assets/icon/love_your_answer.jpg',
    },
    {
      nombre: 'Map Of The Soul 7',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$31.990',
      portada: 'assets/icon/map_of_the_soul.jpg',
    },
    {
      nombre: 'The Astronaut',
      artista: 'JIN',
      genero: 'K-pop',
      precio: '$23.990',
      portada: 'assets/icon/astronaut.jpg',
    },
    {
      nombre: 'D-DAY',
      artista: 'Agust D',
      genero: 'K-pop',
      precio: '$25.990',
      portada: 'assets/icon/d_day.jpg',
    },
    {
      nombre: 'FACE',
      artista: 'JIMIN',
      genero: 'K-pop',
      precio: '$26.990',
      portada: 'assets/icon/face.jpg',
    },
    {
      nombre: 'Jack In The Box',
      artista: 'J-Hope',
      genero: 'K-pop',
      precio: '$24.990',
      portada: 'assets/icon/jack_in_the_box.jpg',
    },
    {
      nombre: 'Golden',
      artista: 'JungKook',
      genero: 'K-pop',
      precio: '$29.990',
      portada: 'assets/icon/jk_golden.jpg',
    },
    {
      nombre: 'Muse',
      artista: 'JIMIN',
      genero: 'K-pop',
      precio: '$29.990',
      portada: 'assets/icon/muse.jpg',
    },
    {
      nombre: 'Are You Late Too [O!RUL8,2]',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$23.990',
      portada: 'assets/icon/ohareyou.jpg',
    },
    {
      nombre: '2 COOL 4 SKOOL',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$17.990',
      portada: 'assets/icon/2kool4.jpg',
    },
    {
      nombre: 'Dark & Wild',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$25.990',
      portada: 'assets/icon/dark_wild.jpg',
    },
    {
      nombre: 'Map Of The Soul Persona',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$24.990',
      portada: 'assets/icon/persona.jpg',
    },
    {
      nombre: 'Skool Luv Affair',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$23.990',
      portada: 'assets/icon/skool_luv.jpg',
    },
    {
      nombre: 'The Most Beautiful Moment in Life PT.1',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$20.990',
      portada: 'assets/icon/the_most_1.jpg',
    },
    {
      nombre: 'The Most Beautiful Moment in Life PT.2',
      artista: 'BTS',
      genero: 'K-pop',
      precio: '$20.990',
      portada: 'assets/icon/the_most_2.jpg',
    },
    {
      nombre: 'Indigo',
      artista: 'RM',
      genero: 'K-pop',
      precio: '$26.990',
      portada: 'assets/icon/indigo.jpg',
    },
    {
      nombre: 'Golden Hour Part.1',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$29.990',
      portada: 'assets/icon/golden_hour.jpg',
    },
    {
      nombre: 'The World Ep.Fin : Will',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$27.990',
      portada: 'assets/icon/michinpum.jpg',
    },
    {
      nombre: 'The World Ep.2 : Outlaw',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$28.990',
      portada: 'assets/icon/bouncy.jpg',
    },
    {
      nombre: 'The World Ep.1 : Movement',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$27.990',
      portada: 'assets/icon/guerrilla.jpg',
    },
    {
      nombre: 'Zero : Fever Part.1',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$32.990',
      portada: 'assets/icon/fever_1.jpg',
    },
    {
      nombre: 'Zero : Fever Part.2',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$29.990',
      portada: 'assets/icon/fever_2.jpg',
    },
    {
      nombre: 'Zero : Fever Part.3',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$29.990',
      portada: 'assets/icon/fever_3.jpg',
    },
    {
      nombre: 'Beyond : Zero (Limited Edition)',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$40.990',
      portada: 'assets/icon/rocky.jpg',
    },
    {
      nombre: '(Pre-Venta) Fix On / Off',
      artista: 'MINGI',
      genero: 'K-pop',
      precio: '$64.990',
      portada: 'assets/icon/Mingi.jpg',
    },
    {
      nombre: 'Treasure Ep.1 : All To Zero',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$20.990',
      portada: 'assets/icon/treasure_1.jpg',
    },
    {
      nombre: 'Treasure Ep.2 : Zero To One',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$24.990',
      portada: 'assets/icon/treasure_2.jpg',
    },
    {
      nombre: 'Treasure Ep.3 : One To All',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$17.990',
      portada: 'assets/icon/treasure_3.jpg',
    },
    {
      nombre: 'Treasure Ep.Fin : All To Action',
      artista: 'ATEEZ',
      genero: 'K-pop',
      precio: '$20.990',
      portada: 'assets/icon/treasure_fin_all.jpg',
    },
    {
      nombre: 'Romance : Untold',
      artista: 'ENHYPEN',
      genero: 'K-pop',
      precio: '$28.990',
      portada: 'assets/icon/xo.jpg',
    },
    {
      nombre: 'Orange Blood',
      artista: 'ENHYPEN',
      genero: 'K-pop',
      precio: '$26.990',
      portada: 'assets/icon/orange_blood.jpg',
    },
    {
      nombre: 'Dark Blood',
      artista: 'ENHYPEN',
      genero: 'K-pop',
      precio: '$27.990',
      portada: 'assets/icon/dark_blood.jpg',
    },
    {
      nombre: 'Border : Day One',
      artista: 'ENHYPEN',
      genero: 'K-pop',
      precio: '$31.990',
      portada: 'assets/icon/given_taken.jpg',
    },
    {
      nombre: 'Dimension : Dilema',
      artista: 'ENHYPEN',
      genero: 'K-pop',
      precio: '$16.990',
      portada: 'assets/icon/dimension_dilemma.jpg',
    },
    {
      nombre: 'Memorabilia',
      artista: 'ENHYPEN',
      genero: 'K-pop',
      precio: '$31.990',
      portada: 'assets/icon/memorabilia.jpg',
    },
  ];
  
  constructor(private router: Router) {}

  ngOnInit() {
  }
}